---
title: "00_all.qmd"
format: html
editor: visual
---

## Load Data

```{r}
quarto::quarto_render(input = "01_load.qmd",
                      output_format = "html")

file.rename(from = "01_load.html",
            to = "../results/01_load.html")
```

## Clean Data

```{r}
quarto::quarto_render(input = "02_clean.qmd", 
                      output_format = "html")

file.rename(from = "02_clean.html",
            to = "../results/02_clean.html")
```

## Augment Data

```{r}
quarto::quarto_render(input = "03_augment.qmd", 
                      output_format = "html")

file.rename(from = "03_augment.html",
            to = "../results/03_augment.html")
```

## Description

```{r}
quarto::quarto_render(input = "04_description.qmd", 
                      output_format = "html")

file.rename(from = "04_description.html",
            to = "../results/04_description.html")
```

## Visualizations

```{r}
quarto::quarto_render(input = "05_visualizations.qmd", 
                      output_format = "html")


file.rename(from = "05_visualizations.html",
            to = "../results/05_visualizations.html")
```

## PCA analysis

```{r}
quarto::quarto_render(input = "06_analysis_PCA.qmd",
                      output_format = "html")

file.rename(from = "06_analysis_PCA.html",
            to = "../results/06_analysis_PCA.html")
```

## Shiny

```{r}
quarto::quarto_render(input = "07_shiny.qmd",
                      output_format = "html")

file.rename(from = "07_shiny.html",
            to = "../results/07_shiny.html")
```

## All

```{r}

file.rename(from = "00_all.html",
            to = "../results/00_all.html")
```
