---
title: "05_age_gender_diagnoses"
author: "Rolf"
format: html
editor: visual
---

## Load libraries

```{r, message=FALSE}
suppressWarnings({
library("tidyverse")
library("ggplot2")
library("dplyr")
library("tidyr")
library("here")
})
```

## Load data

```{r}
data <- read.csv(here("data/02_dat_clean.csv"))
```

## Boxplot

```{r}
data1 <- data |>
  filter(gender != "Unknown/Invalid") |>
  group_by(age, gender) |> 
  summarize(average_diagnoses = mean(number_diagnoses), .groups = "drop")

bp1 <- ggplot(
  data = data1,
  mapping = aes(x = age,
                y = average_diagnoses,
                fill = gender)
) +
  geom_col(position = "dodge") +
  labs(x = "Age Group",
       y = "Average number of diagnoses",
       color = "Gender",
       Title = "Average number of diagnoses for all age groups and genders")

bp1
```

## Same boxplot, but facet wrapping for race

```{r}
barplot1 <- data |>
  filter(gender != "Unknown/Invalid", 
         race != "Other") |>
  group_by(age, 
           gender, 
           race) |> 
  summarize(average_diagnoses = mean(number_diagnoses), .groups = "drop") |> 
ggplot(
  mapping = aes(x = age,
                y = average_diagnoses,
                fill = gender)
) +
  geom_col(position = "dodge", 
           alpha = 1.0) +
  facet_wrap(~ race) +
  labs(
    x = "Age Group",
    y = "Average number of diagnoses",
    fill = "Gender",
    title = "Average number of diagnoses for all age groups and genders facet wrapped for race"
  ) +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 60, hjust =1)
    )

barplot1
```

## Discharge diposition

```{r, fig.width=8, fig.height=6}
bp3 <- data |>
  group_by(discharge_disposition,
           gender,
           age)|> 
  summarize(n = n()) |> 
  ggplot(
    mapping = aes(x = discharge_disposition,
                  y = n,
                  fill = age)
  ) +
  geom_col(position = "dodge") +
  labs(
    x = "Discharge type",
    y = "Count",
    fill = "Age group",
    title = "Discharge type for all age groups for all admission types"
  ) +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 60, hjust =1)
    )
bp3
```

### Only for emergency admission type

```{r, fig.width=8, fig.height=6}
bp4 <- data |>
  filter(!discharge_disposition %in% c("NULL",
                                       "Not Available",
                                       "Not Mapped"),
         admission_type == "Emergency") |> 
  group_by(discharge_disposition,
           gender,
           age)|> 
  summarize(n = n()) |> 
  ggplot(
    mapping = aes(x = discharge_disposition,
                  y = n,
                  fill = age)
  ) +
  geom_col(position = "dodge") +
  labs(
    x = "Discharge type",
    y = "Count",
    fill = "Age group",
    title = "Discharge type for all age groups for emergency admissions"
  ) +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 60, hjust =1)
    )
bp4
```

### Only urgent admission type:

```{r, fig.width=8, fig.height=6}
bp5 <- data |>
  filter(gender != "Unknown/Invalid",
         !discharge_disposition %in% c("NULL",
                                       "Not Available",
                                       "Not Mapped"),
         admission_type == "Urgent") |> 
  group_by(discharge_disposition,
           gender,
           age)|> 
  summarize(n = n()) |> 
  ggplot(
    mapping = aes(x = discharge_disposition,
                  y = n,
                  fill = age)
  ) +
  geom_col(position = "dodge") +
  labs(
    x = "Discharge type",
    y = "Count",
    fill = "Age group",
    title = "Discharge type for all age groups for urgent admissions"
  ) +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 60, hjust =1)
    )
bp5
```

### For elective admission type

```{r, fig.width=8, fig.height=6}
bp6 <- data |>
  filter(gender != "Unknown/Invalid",
         !discharge_disposition %in% c("NULL",
                                       "Not Available",
                                       "Not Mapped"),
         admission_type == "Elective") |> 
  group_by(discharge_disposition,
           gender,
           age)|> 
  summarize(n = n()) |> 
  ggplot(
    mapping = aes(x = discharge_disposition,
                  y = n,
                  fill = age)
  ) +
  geom_col(position = "dodge") +
  labs(
    x = "Discharge type",
    y = "Count",
    fill = "Age group",
    title = "Discharge type for all age groups for elective admissions"
  ) +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 60, hjust =1)
    )
bp6
```
