---
title: "PCA analysis"
format: html
editor: visual
---

### Import dataset

This is an example trial run. The real data should be imported below as clean data:

```{r}
library(tidyverse)
library(broom)  # devtools::install_github("tidymodels/broom")
library(cowplot)
data <- read_csv(here("data/02_dat_clean.csv"))
```

### Start of the PCA

Looking at the data in PC coordinates.

```{r}
numeric_data <- data |> 
  select(where(is.numeric)) |> 
  na.omit()

pca_fit <- numeric_data |>  
  prcomp(scale = TRUE) # do PCA on scaled data

data_clean <- data |> 
  filter(row_number() %in% rownames(numeric_data))

pca_plot <- pca_fit |> 
  augment(data_clean) |>  # add original dataset back in
  ggplot(aes(.fittedPC1, .fittedPC2)) + 
  geom_point(size = 1.5) +
  theme_half_open(12) +
  background_grid()
```

Now we extract the rotation matrix

```{r}
# extract rotation matrix
pca_fit |> 
  tidy(matrix = "rotation")
```

and plot it:

```{r}
# define arrow style for plotting
arrow_style <- arrow(
  angle = 20, ends = "first", type = "closed", length = grid::unit(8, "pt")
)

# plot rotation matrix
pca_fit |> 
  tidy(matrix = "rotation") |> 
  pivot_wider(names_from = "PC",
              names_prefix = "PC",
              values_from = "value") |> 
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0,
               yend = 0,
               arrow = arrow_style) +
  geom_text(
    aes(label = column),
    hjust = 1, nudge_x = -0.02, 
    color = "#904C2F"
  ) +
  xlim(-1.25, .5) +
  ylim(-.5, 1) +
  coord_fixed() +  # fix aspect ratio to 1:1
  theme_minimal_hgrid(12)
```

Look at the variance

```{r}
pca_fit |> 
  tidy(matrix = "eigenvalues")
```

And now the plot:

```{r}
pca_fit |> 
  tidy(matrix = "eigenvalues") |> 
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9",
           alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  theme_minimal_hgrid(12)
```

### Exporting the key plots

```{r}
ggsave(
  filename = here("results", "pca_plot.png"),  # path to save
  plot = pca_plot, 
  width = 8, 
  height = 6, 
  dpi = 300
)

ggsave(
  filename = here("results", "pca_bar_plot.png"),  # path to save
  plot = pca_bar_plot, 
  width = 8, 
  height = 6, 
  dpi = 300
)
```
